services:
  api:
    container_name: mytravels-api
    image: mytravels-api:v1.0.8
    build:
      context: ../intro-to-k8s/src
      dockerfile: api/mytravels.api/Dockerfile
    environment:
      ConnectionStrings__CoreDbContext: ${CORE_DB_CONTEXT}
      GoogleApiKey: ${GOOGLE_API_KEY}
      GoogleMapsUrl: ${GOOGLE_MAPS_URL}
      GooglePlacesUrl: ${GOOGLE_PLACES_URL}
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      ASPNETCORE_URLS: ${ASPNETCORE_URLS}
      RabbitMQ__Uri: ${RABBIT_MQ_URI}
      MinIO__Endpoint: ${MINIO_ENDPOINT}
      MinIO__AccessKey: ${MINIO_ROOT_USER}
      MinIO__SecretKey: ${MINIO_ROOT_PASSWORD}
    ports:
      - "5101:5101"
    depends_on:
      rabbitmq:
        condition: service_healthy
